# Generated by Django 4.2.3 on 2023-08-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniwallpapers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorauth',
            name='portfolio',
            field=models.FileField(upload_to='portfolios'),
        ),
    ]
