# Generated by Django 4.2.3 on 2023-08-13 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniwallpapers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Creatorauth',
        ),
    ]
