# Generated by Django 4.2.3 on 2023-08-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miniwallpapers', '0002_delete_creatorauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creatorauth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('portfolio', models.FileField(upload_to='portfolio')),
            ],
        ),
    ]
