# Generated by Django 4.2.3 on 2023-08-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniwallpapers', '0004_userprofiledoc_delete_creatorauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiledoc',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
