# Generated by Django 4.2.3 on 2023-08-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniwallpapers', '0006_category_tag_wallpapercollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpapercollection',
            name='wallpaper_image',
            field=models.ImageField(default='path_to_default_image.jpg', upload_to='wallpapers/'),
        ),
    ]
