# Generated by Django 4.2.3 on 2023-08-19 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniwallpapers', '0007_wallpapercollection_wallpaper_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpapercollection',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='miniwallpapers.category'),
        ),
        migrations.AlterField(
            model_name='wallpapercollection',
            name='tags',
            field=models.ManyToManyField(default=None, to='miniwallpapers.tag'),
        ),
    ]
