# Generated by Django 4.2.3 on 2023-09-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniwallpapers', '0008_alter_wallpapercollection_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpapercollection',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
