# Generated by Django 4.2.3 on 2023-09-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniwallpapers', '0009_wallpapercollection_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='hashtag',
            field=models.CharField(default=2, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('superhero', 'Superhero'), ('nature', 'Nature'), ('wildlife', 'Wildlife'), ('cars', 'Cars'), ('bikes', 'Bikes'), ('ai_arts', 'AI Arts')], default='others', max_length=50),
        ),
    ]
