# Generated by Django 4.2.3 on 2023-09-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniwallpapers', '0010_tag_hashtag_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='hashtag',
            field=models.CharField(default='default_hashtag', max_length=50),
        ),
    ]
