# Generated by Django 4.2.3 on 2023-09-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniwallpapers', '0011_alter_tag_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('superhero', 'Superhero'), ('movie', 'Movie'), ('nature', 'Nature'), ('wildlife', 'Wildlife'), ('cars', 'Cars'), ('bikes', 'Bikes'), ('ai_arts', 'AI Arts')], default='others', max_length=50),
        ),
    ]
