# Generated by Django 4.2.3 on 2023-09-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniwallpapers', '0012_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpapercollection',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
