# Generated by Django 4.2.3 on 2023-09-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniwallpapers', '0013_wallpapercollection_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiledoc',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
