# Generated by Django 4.2.3 on 2023-09-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniwallpapers', '0014_userprofiledoc_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiledoc',
            name='about_me',
            field=models.TextField(blank=True),
        ),
    ]
