# Generated by Django 4.2.3 on 2023-09-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniwallpapers', '0016_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiledoc',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofiledoc',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
