# Generated by Django 4.2.3 on 2023-09-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniwallpapers', '0017_userprofiledoc_is_creator_userprofiledoc_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiledoc',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
