# Generated by Django 4.2.3 on 2023-09-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniwallpapers', '0019_userprofiledoc_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiledoc',
            name='google_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
