# Generated by Django 4.2.3 on 2023-09-25 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('miniwallpapers', '0020_userprofiledoc_google_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiledoc',
            name='google_uid',
        ),
        migrations.AddField(
            model_name='userprofiledoc',
            name='social_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialaccount.socialaccount'),
        ),
    ]
