# Generated by Django 4.2.3 on 2023-09-25 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('miniwallpapers', '0021_remove_userprofiledoc_google_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiledoc',
            name='social_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialaccount.socialaccount'),
        ),
    ]
