# Generated by Django 4.2.3 on 2023-09-26 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniwallpapers', '0022_alter_userprofiledoc_social_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiledoc',
            name='social_account',
        ),
    ]
