# Generated by Django 4.2.3 on 2023-10-05 05:54

from django.db import migrations, models
import miniwallpapers.models


class Migration(migrations.Migration):

    dependencies = [
        ('miniwallpapers', '0023_remove_userprofiledoc_social_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpapercollection',
            name='wallpaper_image',
            field=models.ImageField(default='path_to_default_image.jpg', upload_to=miniwallpapers.models.WallpaperCollection.get_upload_path),
        ),
    ]
