# Generated by Django 4.2.3 on 2023-10-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniwallpapers', '0024_alter_wallpapercollection_wallpaper_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('superhero', 'Superhero'), ('anime', 'Anime'), ('movie', 'Movie'), ('nature', 'Nature'), ('wildlife', 'Wildlife'), ('cars', 'Cars'), ('bikes', 'Bikes'), ('ai_arts', 'AI Arts'), ('others', 'Others')], default='others', max_length=50),
        ),
    ]
