# Generated by Django 4.2.3 on 2023-10-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniwallpapers', '0025_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('superhero', 'Superhero'), ('anime', 'Anime'), ('movie', 'Movie'), ('nature', 'Nature'), ('game', 'Game'), ('wildlife', 'Wildlife'), ('cars', 'Cars'), ('bikes', 'Bikes'), ('ai_arts', 'AI Arts'), ('others', 'Others')], default='others', max_length=50),
        ),
    ]
