# Generated by Django 4.2.3 on 2023-10-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniwallpapers', '0026_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiledoc',
            name='subscription_duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofiledoc',
            name='subscription_expiration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
