# Generated by Django 4.2.3 on 2023-10-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniwallpapers', '0027_userprofiledoc_subscription_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpapercollection',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
