# Generated by Django 4.2.4 on 2024-02-02 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniwallpapers', '0031_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
