# Generated by Django 4.2.4 on 2024-02-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniwallpapers', '0034_alter_wallpapercollection_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpapercollection',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
