# Generated by Django 4.2.4 on 2024-02-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniwallpapers', '0035_alter_wallpapercollection_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='communitychat/'),
        ),
    ]
