# Generated by Django 4.2.4 on 2024-02-12 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniwallpapers', '0036_chatmessage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='image',
        ),
    ]
