# Generated by Django 4.2.4 on 2024-02-19 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniwallpapers', '0039_wallpapercollection_average_rating_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
