# Generated by Django 4.2.4 on 2024-02-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniwallpapers', '0041_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiledoc',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
