# Generated by Django 4.2.4 on 2024-02-23 04:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miniwallpapers', '0042_userprofiledoc_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpapercollection',
            name='downloads_by_user',
            field=models.ManyToManyField(blank=True, related_name='downloads', to=settings.AUTH_USER_MODEL),
        ),
    ]
