# Generated by Django 4.2.4 on 2024-02-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniwallpapers', '0043_wallpapercollection_downloads_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiledoc',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
