# Generated by Django 4.2.4 on 2024-03-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniwallpapers', '0044_alter_userprofiledoc_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpapercollection',
            name='sentiment_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
