# Generated by Django 4.2.4 on 2024-04-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniwallpapers', '0045_wallpapercollection_sentiment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiledoc',
            name='invoice_path',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
